WaterQuality/Controllers/WaterBodyController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization.Json;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Microsoft.AspNet.Identity;
using DotNetOpenAuth.OAuth2;
using EHWaterQuality.Filters;
using EHWaterQuality.Models;
using EHWaterQuality.Repositories;
using EHWaterQuality.Utilities;
using EHWaterQuality.ViewModels;

namespace EHWaterQuality.Controllers
{
    [MacAuthorize(Action = "AdministerAll,AdministerOwn")]
    public class WaterBodyController : BaseController
    {
        private GenericEHWaterQualityUnitOfWork _uow = null;
        private WaterBodyGet _waterBodyRepo = null;

        private string _modifiedBy = null;
        private string _userRole = null;
        //private WebServerClient _webServerClient;
        //private HttpClient _client;
        //private Uri _resourceServerUri = new Uri(ConfigurationManager.AppSettings["OAuth.MacombCounty.Paths.Remote.ResourceServerBaseAddress"]);

        public WaterBodyController()
        {
            _uow = new GenericEHWaterQualityUnitOfWork();
            _waterBodyRepo = new WaterBodyGet();

            if (SessionHelper.UserName == null)
            {
                _modifiedBy = "Test";
            }
            else
            {
                _modifiedBy = SessionHelper.UserName;
            }
        }

        [HttpGet]
        public ViewResult Index(int ID)
        {
            var model = new WaterBodyIndexViewModel()
            {
                ID = ID
            };

            return View(model);
        }

        [HttpGet]
        public JsonResult GetWaterBodies()
        {
            IEnumerable<REF_WATER_BODY_TB> waterBodies = _uow.Repository<REF_WATER_BODY_TB>().GetAll();
            List<WaterBodyIndex> waterBodyList = new List<WaterBodyIndex>();

            waterBodies = waterBodies.ToList().OrderBy(u => u.SZ_DESCRIPTION);

            foreach (var waterBody in waterBodies)
            {
                WaterBodyIndex item = new WaterBodyIndex()
                {
                    WaterBodyDescription = waterBody.SZ_DESCRIPTION == null ? "" : waterBody.SZ_DESCRIPTION,
                    WaterBodyID = waterBody.N_WATER_BODY_SYSID,
                    WaterBodyName = waterBody.SZ_NAME == null ? "" : waterBody.SZ_NAME
                };
                waterBodyList.Add(item);
            }

            return Json(waterBodyList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ViewResult Edit(int ID)
        {
            var waterBodyEditViewModel = new WaterBodyEditViewModel();
            if (ID > 0)
            {
                REF_WATER_BODY_TB waterBody = _uow.Repository<REF_WATER_BODY_TB>().GetById(ID);
                waterBodyEditViewModel.WaterBodyDescription = waterBody.SZ_DESCRIPTION == null ? "" : waterBody.SZ_DESCRIPTION;
                waterBodyEditViewModel.WaterBodyID = waterBody.N_WATER_BODY_SYSID;
                waterBodyEditViewModel.WaterBodyName = waterBody.SZ_NAME == null ? "" : waterBody.SZ_NAME;
                waterBodyEditViewModel.ShowMessageNameAndDescription = false;
                waterBodyEditViewModel.MessageNameAndDescription = "";
            }
            else
            {
                waterBodyEditViewModel.WaterBodyDescription = "";
                waterBodyEditViewModel.WaterBodyID = ID;
                waterBodyEditViewModel.WaterBodyName = "";
                waterBodyEditViewModel.ShowMessageNameAndDescription = false;
                waterBodyEditViewModel.MessageNameAndDescription = "";
            }

            return View("Edit", waterBodyEditViewModel);
        }

        [HttpPost]
        public ActionResult Edit(WaterBodyEditViewModel Model)
        {
            if (_waterBodyRepo.IsWaterBodyNameAndDescriptionDuplicate(Model.WaterBodyName, Model.WaterBodyDescription))
            {
                Model.ShowMessageNameAndDescription = true;
                Model.MessageNameAndDescription = "The Water Body Name and Description combination already exists. Please enter a different one.";

                return View(Model);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    int id = 0;
                    if (Model.WaterBodyID == 0) //new
                    {
                        REF_WATER_BODY_TB waterBody = new REF_WATER_BODY_TB()
                        {
                            B_INACTIVE = false,
                            DT_ENTERED = DateTime.UtcNow,
                            DT_MODIFIED = DateTime.UtcNow,
                            SZ_ENTERED_BY = _modifiedBy,
                            SZ_MODIFIED_BY = _modifiedBy,
                            SZ_DESCRIPTION = Model.WaterBodyDescription,
                            SZ_NAME = Model.WaterBodyName
                        };
                        _uow.Repository<REF_WATER_BODY_TB>().Add(waterBody);
                        _uow.SaveChanges();
                        REF_WATER_BODY_TB waterBodyFound = _uow.Repository<REF_WATER_BODY_TB>().Find(u => u.SZ_ENTERED_BY == _modifiedBy
                            && u.SZ_MODIFIED_BY == _modifiedBy && u.SZ_DESCRIPTION == Model.WaterBodyDescription
                            && u.SZ_NAME == Model.WaterBodyName).FirstOrDefault();
                        id = waterBodyFound.N_WATER_BODY_SYSID;
                    }
                    else //edit
                    {
                        REF_WATER_BODY_TB waterBody = _uow.Repository<REF_WATER_BODY_TB>().GetById(Model.WaterBodyID);
                        waterBody.DT_MODIFIED = DateTime.UtcNow;
                        waterBody.SZ_DESCRIPTION = Model.WaterBodyDescription;
                        waterBody.SZ_MODIFIED_BY = _modifiedBy;
                        waterBody.SZ_NAME = Model.WaterBodyName;

                        _uow.Repository<REF_WATER_BODY_TB>().Update(waterBody);
                        _uow.SaveChanges();
                        id = Model.WaterBodyID;
                    }

                    return RedirectToAction("Index", new { ID = id });
                }

                return View(Model);
            }
        }

        [HttpGet]
        public ActionResult Delete(string ID)
        {
            try
            {
                REF_WATER_BODY_TB waterBody = _uow.Repository<REF_WATER_BODY_TB>().GetById(Convert.ToInt32(ID));
                WaterBodyDeleteViewModel waterBodyDeleteViewModel = new WaterBodyDeleteViewModel()
                {
                    WaterBodyID = waterBody.N_WATER_BODY_SYSID,
                    WaterBodyName = waterBody.SZ_NAME,
                    WaterBodyDescription = waterBody.SZ_DESCRIPTION,
                    MessageNameAndDescription = "",
                    ShowMessageNameAndDescription = false
                };

                return View(waterBodyDeleteViewModel);
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewBag.Message = "Function: WaterBodyController.Delete_GET\n\nError: " + ex.Message;
                }
                else
                {
                    ViewBag.Message = "Function: WaterBodyController.Delete_GET\n\nError: " + (ex.Message + "\n\nInnerException: " + ex.InnerException.Message);
                };
                Session["ErrorMessage"] = ViewBag.Message;
                return RedirectToAction("InternalServerError", "Error");
            };
        }

        [HttpPost]
        public ActionResult Delete(WaterBodyDeleteViewModel model)
        {
            try
            {
                int id = Convert.ToInt32(model.WaterBodyID);
                if (_uow.Repository<REF_LOCATION_TB>().Find(u => u.N_WATER_BODY_SYSID == id).Count() > 0 ||
                    _uow.Repository<TRN_SEWER_OVERFLOW_TB>().Find(u => u.N_WATER_BODY_SYSID == id).Count() > 0)
                {
                    model.ShowMessageNameAndDescription = true;
                    model.MessageNameAndDescription = "Records exist for this water body. Sorry, the water body can not be deleted.";

                    return View(model);
                }
                else
                {
                    _uow.Repository<REF_WATER_BODY_TB>().Delete(id);
                    _uow.SaveChanges();

                    return RedirectToAction("Index", new { ID = id });
                }
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewBag.Message = "Function: WaterBodyController.Delete_POST\n\nError: " + ex.Message;
                }
                else
                {
                    ViewBag.Message = "Function: WaterBodyController.Delete_POST\n\nError: " + (ex.Message + "\n\nInnerException: " + ex.InnerException.Message);
                };
                Session["ErrorMessage"] = ViewBag.Message;
                return RedirectToAction("InternalServerError", "Error");
            };   
        }
    }
}

WaterQuality/Views/WaterBody/Delete.cshtml
@using EHWaterQuality.ViewModels
@model WaterBodyDeleteViewModel
@{
    ViewBag.Title = "Delete Water Body";
}

<!-- BEGIN PAGE CONTENT -->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="row">
        @using (Html.BeginForm("Delete", "WaterBody", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
        {
            <div class="row">
                <label class="control-label col-md-2">Name</label>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.WaterBodyName)
                    @Html.HiddenFor(model => model.WaterBodyName)
                    @Html.HiddenFor(model => model.WaterBodyID)
                    @if (Model.ShowMessageNameAndDescription == true)
                    {
                        <span style="color:red">@Html.DisplayFor(m => m.MessageNameAndDescription)</span>
                    }
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <label class="control-label col-md-2">Description</label>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.WaterBodyDescription)
                    @Html.HiddenFor(model => model.WaterBodyDescription)
                    @if (Model.ShowMessageNameAndDescription == true)
                    {
                        <span style="color:red">@Html.DisplayFor(m => m.MessageNameAndDescription)</span>
                    }
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <button type="submit" class="btn blue">Delete</button>
                    <button type="button" class="btn blue" id="back">Back</button>
                </div>
            </div>
        }
    </div>
    @section PageLevelScripts {
        <script>
            $(document).ready(function () {
                $("#back").on('click', function () {
                    var model = @Html.Raw(Json.Encode(Model));
                    var id = model.WaterBodyID;
                    var url = '@Url.Action("Index", "WaterBody", new { ID = "_id_" })'.replace('_id_', id);
                    window.location.href = url;
                })
            })
        </script>
    }
</body>
</html>
<!-- END PAGE CONTENT -->

WaterQuality/Views/WaterBody/Edit.cshtml
@using EHWaterQuality.ViewModels
@model WaterBodyEditViewModel
@{
    ViewBag.Title = "Edit / New Water Body";
}

<!-- BEGIN PAGE CONTENT -->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="row">
        @using (Html.BeginForm("Edit", "WaterBody", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
        {
            <div class="row">
                <label class="control-label col-md-2"><span class="required">* </span>Name</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.WaterBodyName, new { style = "width:300px;" })
                    <span style="color:red">@Html.ValidationMessageFor(model => model.WaterBodyName)</span>
                    @Html.HiddenFor(model => model.WaterBodyID)
                    @if (Model.ShowMessageNameAndDescription == true)
                    {
                        <span style="color:red">@Html.DisplayFor(m => m.MessageNameAndDescription)</span>
                    }
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <label class="control-label col-md-2"><span class="required">* </span>Description</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.WaterBodyDescription, new { style = "width:300px;" })
                    <span style="color:red">@Html.ValidationMessageFor(model => model.WaterBodyDescription)</span>
                    @if (Model.ShowMessageNameAndDescription == true)
                    {
                        <span style="color:red">@Html.DisplayFor(m => m.MessageNameAndDescription)</span>
                    }
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <button type="submit" class="btn blue">Save</button>
                    <button type="button" class="btn blue" id="back">Back</button>
                </div>
            </div>
        }
    </div>
    @section PageLevelScripts {
        <script>
            $(document).ready(function () {
                $("#back").on('click', function () {
                    var model = @Html.Raw(Json.Encode(Model));
                    var id = model.WaterBodyID;
                    var url = '@Url.Action("Index", "WaterBody", new { ID = "_id_" })'.replace('_id_', id);
                    window.location.href = url;
                })
            })
        </script>
    }
</body>
</html>
<!-- END PAGE CONTENT -->

WaterQuality/Views/WaterBody/Index.cshtml
@using EHWaterQuality.ViewModels
@model WaterBodyIndexViewModel
@{
    ViewBag.Title = "Maintain Water Bodies";
}

<!-- BEGIN PAGE CONTENT -->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-edit"></i>Water Bodies
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                    Select Water Body and <button type="button" class="btn blue" id="edit">Edit</button>
                    <button type="button" class="btn blue" id="delete">Delete</button> |
                    <button type="button" id="new" class="btn blue">
                        New Water Body <i class="fa fa-plus"></i>
                    </button>
                    <br />
                    <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                        <thead>
                            <tr>
                                <th>
                                    Select
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Description
                                </th>
                            </tr>
                        </thead>
                        <tbody id="waterBodies"></tbody>
                        <tfoot>
                            <tr>
                                <th>
                                    Select
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Description
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                    Select Water Body and <button type="button" class="btn blue" id="edit2">Edit</button>
                    <button type="button" class="btn blue" id="delete2">Delete</button> |
                    <button type="button" id="new2" class="btn blue">
                        New Water Body <i class="fa fa-plus"></i>
                    </button>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    @section PageLevelScripts {
        <script>
    $(document).ready(function () {
        GetWaterBodies();
    })

    $('#edit').click(function () {
        EditWaterBody();
    })

    $('#edit2').click(function () {
        EditWaterBody();
    })

    $('#delete').click(function () {
        DeleteWaterBody();
    })

    $('#delete2').click(function () {
        DeleteWaterBody();
    })

    $('#new').click(function () {
        NewWaterBody();
    })

    $('#new2').click(function () {
        NewWaterBody();
    })

    function GetWaterBodies() {
        $.ajaxSetup({ cache: false });
        var url = '@Url.Action("GetWaterBodies", "WaterBody")';
        $.getJSON(url, function (response) {
            if (response.length) {
                var row = "";
                $.each(response, function (index, item) {
                    row += "<tr><td><input type='checkbox' id='waterBodyCheckbox' name='" + item.WaterBodyID + "'" +
                        " class='my_chkBox' /></td><td>" + item.WaterBodyName +
                        "</td><td>" + item.WaterBodyDescription +
                        "</td></tr>";
                })
                $("#waterBodies").html(row);
                $("#waterBodies").find(":checkbox").click(function () {
                    $("#waterBodies").find(":checkbox").removeAttr("checked");
                    $(this).prop("checked", true);
                })
                SelectedWaterBody();
            }
            else {
                $("#waterBodies").html("<div class='col-md-12'><h2 style='color:red'>No records found.</h2></div>");
            }
        });
    }

    function SelectedWaterBody() {
        var model = @Html.Raw(Json.Encode(Model));
        var id = model.ID;
        if (id != "0") {
            $('#waterBodies').find(':checkbox').each(function () {
                if ($(this).prop("name").toString() == id) {
                    $(this).prop('checked', true);
                }
            })
        }
    }

    function EditWaterBody() {
        var id = 0;
        $('#waterBodies').find(':checkbox').each(function () {
            if ($(this).prop("checked") == true) {
                id = $(this).prop("name").toString();
                return false;
            }
        })
        if (id == 0) {
            alert("Please select a Water Body for edit");
        }
        else {
            var url = '@Url.Action("Edit", "WaterBody", new { ID = "_id_" })'.replace('_id_', id);
            window.location.href = url;
        }
    }

    function DeleteWaterBody() {
        var id = 0;
        $('#waterBodies').find(':checkbox').each(function () {
            if ($(this).prop("checked") == true) {
                id = $(this).prop("name").toString();
                return false;
            }
        })
        if (id == 0) {
            alert("Please select a Water Body for delete");
        }
        else {
            var url = '@Url.Action("Delete", "WaterBody", new { ID = "_id_" })'.replace('_id_', id);
            window.location.href = url;
        }
    }

    function NewWaterBody() {
        var id = 0;
        var url = '@Url.Action("Edit", "WaterBody", new { ID = "_id_" })'.replace('_id_', id);
        window.location.href = url;
    }
        </script>
    }
</body>
</html>
<!-- END PAGE CONTENT -->