WaterQuality/Controllers/SampleTblController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Reflection;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using log4net;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Microsoft.AspNet.Identity;
using DotNetOpenAuth.OAuth2;
using EHWaterQuality.Filters;
using EHWaterQuality.Models;
using EHWaterQuality.Repositories;
using EHWaterQuality.Utilities;
using EHWaterQuality.ViewModels;

namespace EHWaterQuality.Controllers
{
    [MacAuthorize(Action = "AdministerAll,AdministerOwn")]
    public class SampleTblController : BaseController
    {
        private GenericEHWaterQualityUnitOfWork _uow = null;
        private SampleTblGet _sampleTblRepo = null;

        private string _modifiedBy = null;
        private string _userRole = null;
        //private WebServerClient _webServerClient;
        //private HttpClient _client;
        //private Uri _resourceServerUri = new Uri(ConfigurationManager.AppSettings["OAuth.MacombCounty.Paths.Remote.ResourceServerBaseAddress"]);
        protected static readonly ILog log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);

        public SampleTblController()
        {
            _uow = new GenericEHWaterQualityUnitOfWork();
            _sampleTblRepo = new SampleTblGet();
            if (SessionHelper.UserName == null)
            {
                _modifiedBy = "Test";
            }
            else
            {
                _modifiedBy = SessionHelper.UserName;
            }
        }

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewBag.Message = "Function: SampleTblController.Index_GET\n\nError: " + ex.Message;
                }
                else
                {
                    ViewBag.Message = "Function: SampleTblController.Index_GET\n\nError: " + (ex.Message + "\n\nInnerException: " + ex.InnerException.Message);
                };
                Session["ErrorMessage"] = ViewBag.Message;
                return RedirectToAction("InternalServerError", "Error");
            };
        }

        [HttpGet]
        public ActionResult GetSamples()
        {
            try
            {
                IEnumerable<TRN_SAMPLE_TB> samples = _uow.Repository<TRN_SAMPLE_TB>().GetAll();
                List<SampleTblIndexViewModel> sampleList = new List<SampleTblIndexViewModel>();

                foreach (var sample in samples.OrderBy(u => u.N_SAMPLE_SYSID))
                {
                    string location = _uow.Repository<REF_LOCATION_TB>().Find(u => u.N_LOCATION_SYSID == sample.N_LOCATION_SYSID).FirstOrDefault().SZ_LABEL;

                    SampleTblIndexViewModel item = new SampleTblIndexViewModel()
                    {
                        CollectedBy = sample.SZ_COLLECTED_BY,
                        CollectedTime = sample.N_COLLECTED_TIME,
                        DateCollected = sample.DT_COLLECTED.ToShortDateString(),
                        Location = location,
                        SampleID = sample.N_SAMPLE_SYSID.ToString()
                    };
                    sampleList.Add(item);
                }

                return Json(sampleList, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewBag.Message = "Function: SampleTblController.GetSamples_GET\n\nError: " + ex.Message;
                }
                else
                {
                    ViewBag.Message = "Function: SampleTblController.GetSamples_GET\n\nError: " + (ex.Message + "\n\nInnerException: " + ex.InnerException.Message);
                };
                Session["ErrorMessage"] = ViewBag.Message;
                return RedirectToAction("InternalServerError", "Error");
            };
        }

        [HttpGet]
        public ActionResult Delete(SampleTblDeleteViewModel model)
        {
            try
            {
                TRN_SAMPLE_TB sample = _uow.Repository<TRN_SAMPLE_TB>().GetById(model.ID);
                SampleTblDeleteViewModel sampleTblDeleteViewModel = new SampleTblDeleteViewModel()
                {
                    ID = sample.N_SAMPLE_SYSID,
                    Message = "",
                    ShowMessage = false
                };

                return View("Delete", sampleTblDeleteViewModel);
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewBag.Message = "Function: SampleTblController.Delete_GET\n\nError: " + ex.Message;
                }
                else
                {
                    ViewBag.Message = "Function: SampleTblController.Delete_GET\n\nError: " + (ex.Message + "\n\nInnerException: " + ex.InnerException.Message);
                };
                Session["ErrorMessage"] = ViewBag.Message;
                return RedirectToAction("InternalServerError", "Error");
            };
        }

        [HttpPost]
        public ActionResult DeleteSample(SampleTblDeleteViewModel model)
        {
            try
            {
                int id = Convert.ToInt32(model.ID);
                if (_uow.Repository<TRN_RESULT_TB>().Find(u => u.N_SAMPLE_SYSID == id).Count() > 0)
                {
                    model.ShowMessage = true;
                    model.Message = "Result records exist for this Sample. Sorry, the Sample can not be deleted.";

                    return View("Delete", model);
                }
                else
                {
                    _uow.Repository<TRN_SAMPLE_TB>().Delete(id);
                    _uow.SaveChanges();

                    return RedirectToAction("Index", new { ID = id });
                }
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewBag.Message = "Function: SampleTblController.Delete_POST\n\nError: " + ex.Message;
                }
                else
                {
                    ViewBag.Message = "Function: SampleTblController.Delete_POST\n\nError: " + (ex.Message + "\n\nInnerException: " + ex.InnerException.Message);
                };
                Session["ErrorMessage"] = ViewBag.Message;
                return RedirectToAction("InternalServerError", "Error");
            };
        }
    }
}

WaterQuality/Views/SampleTbl/Delete.cshtml
@using EHWaterQuality.ViewModels
@model SampleTblDeleteViewModel
@{
    ViewBag.Title = "Delete Samples";
}

<!-- BEGIN PAGE CONTENT -->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="row">
        @if (Model.ShowMessage == true)
        {
            <div class='col-md-12'><h2 style='color:red'>@Html.DisplayFor(m => m.Message)</h2></div>
        }
        <br />
        <br />
    </div>
    <div class="row">
        @using (Html.BeginForm("DeleteSample", "SampleTbl", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
        {
            <label class="control-label col-md-2">Sample</label>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ID)
                @Html.HiddenFor(model => model.ID)
            </div>
            <br />
            <br />
            <br />
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <button type="submit" class="btn blue">Delete</button>
                    <button type="button" class="btn blue" id="back">Back</button>
                </div>
            </div>
        }
    </div>
    @section PageLevelScripts {
        <script>
            $(document).ready(function () {
                $("#back").on('click', function () {
                    var model = @Html.Raw(Json.Encode(Model));
                    var id = model.ID;
                    var url = '@Url.Action("Index", "SampleTbl", new { ID = "_id_" })'.replace('_id_', id);
                    window.location.href = url;
                })
            })
        </script>
    }
</body>
</html>
<!-- END PAGE CONTENT -->

WaterQuality/Views/SampleTbl/Index.cshtml
@{
    ViewBag.Title = "Delete Samples";
}

<!-- BEGIN PAGE CONTENT -->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="row">
        <div class="col-md-6">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-delete"></i>Sample
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <span>Select Sample and </span><button type="button" class="btn btn-delete btn-default" id="delete">Delete</button>
                    <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                        <thead>
                            <tr>
                                <th>
                                    Select
                                </th>
                                <th>
                                    Sample ID
                                </th>
                                <th>
                                    Location
                                </th>
                                <th>
                                    Collected By
                                </th>
                                <th>
                                    Date Collected
                                </th>
                                <th>
                                    Collected Time
                                </th>
                            </tr>
                        </thead>
                        <tbody id="samples"></tbody>
                        <tfoot>
                            <tr>
                                <th>
                                    Select
                                </th>
                                <th>
                                    Sample ID
                                </th>
                                <th>
                                    Location
                                </th>
                                <th>
                                    Collected By
                                </th>
                                <th>
                                    Date Collected
                                </th>
                                <th>
                                    Collected Time
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                    <span>Select Sample and </span><button type="button" class="btn btn-delete btn-default" id="delete2">Delete</button>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    @section PageLevelScripts {
        <script>
            $(document).ready(function () {
                GetSamples();
            })

            $('#delete').click(function () {
                DeleteSample();
            })

            $('#delete2').click(function () {
                DeleteSample();
            })

            function GetSamples() {
                $.ajaxSetup({ cache: false });
                var url = '@Url.Action("GetSamples", "SampleTbl")';
                $.getJSON(url, function (response) {
                    if (response.length) {
                        var row = "";
                        $.each(response, function (index, item) {
                            row += "<tr><td><input type='checkbox' id='sampleCheckbox' name='" + item.SampleID + "'" +
                                " class='my_chkBox' /></td><td>" + item.SampleID + "</td><td>" + item.Location + "</td><td>" + item.CollectedBy + "</td><td>" + item.DateCollected + "</td><td>" + item.CollectedTime + "</td></tr>";
                        })
                        $("#samples").html(row);
                        $("#samples").find(":checkbox").click(function () {
                            $("#samples").find(":checkbox").removeAttr("checked");
                            $(this).prop("checked", true);
                        })
                        SelectedSample();
                    }
                    else {
                        $("#samples").html("<div class='col-md-12'><h2 style='color:red'>No records found.</h2></div>");
                    }
                });
            }

            function SelectedSample() {
                var model = @Html.Raw(Json.Encode(Model));
                var id = model.ID;
                if (id != "0") {
                    $('#samples').find(':checkbox').each(function () {
                        if ($(this).prop("name").toString() == id) {
                            $(this).prop('checked', true);
                        }
                    })
                }
            }

            function DeleteSample() {
                var id = 0;
                $('#samples').find(':checkbox').each(function () {
                    if ($(this).prop("checked") == true) {
                        id = $(this).prop("name").toString();
                        return false;
                    }
                })
                if (id == 0) {
                    alert("Please select a Sample for delete");
                }
                else {
                    var url = '@Url.Action("Delete", "SampleTbl", new { ID = "_id_" })'.replace('_id_', id);
                    window.location.href = url;
                }
            }
        </script>
    }
</body>
</html>
<!-- END PAGE CONTENT -->