WaterQuality/Controllers/WaterShedController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization.Json;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Microsoft.AspNet.Identity;
using DotNetOpenAuth.OAuth2;
using EHWaterQuality.Filters;
using EHWaterQuality.Models;
using EHWaterQuality.Repositories;
using EHWaterQuality.Utilities;
using EHWaterQuality.ViewModels;

namespace EHWaterQuality.Controllers
{
    [MacAuthorize(Action = "AdministerAll,AdministerOwn")]
    public class WaterShedController : BaseController
    {
        private GenericEHWaterQualityUnitOfWork _uow = null;
        private WaterShedGet _waterShedRepo = null;

        private string _modifiedBy = null;
        private string _userRole = null;
        //private WebServerClient _webServerClient;
        //private HttpClient _client;
        //private Uri _resourceServerUri = new Uri(ConfigurationManager.AppSettings["OAuth.MacombCounty.Paths.Remote.ResourceServerBaseAddress"]);

        public WaterShedController()
        {
            _uow = new GenericEHWaterQualityUnitOfWork();
            _waterShedRepo = new WaterShedGet();

            if (SessionHelper.UserName == null)
            {
                _modifiedBy = "Test";
            }
            else
            {
                _modifiedBy = SessionHelper.UserName;
            }
        }

        [HttpGet]
        public ViewResult Index(int ID)
        {
            var model = new WaterShedIndexViewModel()
            {
                ID = ID
            };

            return View(model);
        }

        [HttpGet]
        public JsonResult GetWaterSheds()
        {
            IEnumerable<REF_LOCATION_TYPE_TB> waterSheds = _uow.Repository<REF_LOCATION_TYPE_TB>().GetAll();
            List<WaterShedIndex> waterShedList = new List<WaterShedIndex>();

            waterSheds = waterSheds.ToList().OrderBy(u => u.SZ_DESCRIPTION);

            foreach (var waterShed in waterSheds)
            {
                WaterShedIndex item = new WaterShedIndex()
                {
                    WaterShedDescription = waterShed.SZ_DESCRIPTION == null ? "" : waterShed.SZ_DESCRIPTION,
                    WaterShedID = waterShed.N_LOCATION_TYPE_SYSID
                };
                waterShedList.Add(item);
            }

            return Json(waterShedList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ViewResult Edit(int ID)
        {
            var waterShedEditViewModel = new WaterShedEditViewModel();
            if (ID > 0)
            {
                REF_LOCATION_TYPE_TB waterShed = _uow.Repository<REF_LOCATION_TYPE_TB>().GetById(ID);
                waterShedEditViewModel.WaterShedDescription = waterShed.SZ_DESCRIPTION == null ? "" : waterShed.SZ_DESCRIPTION;
                waterShedEditViewModel.WaterShedID = waterShed.N_LOCATION_TYPE_SYSID;
                waterShedEditViewModel.ShowMessageDescription = false;
                waterShedEditViewModel.MessageDescription = "";
            }
            else
            {
                waterShedEditViewModel.WaterShedDescription = "";
                waterShedEditViewModel.WaterShedID = ID;
                waterShedEditViewModel.ShowMessageDescription = false;
                waterShedEditViewModel.MessageDescription = "";
            }

            return View("Edit", waterShedEditViewModel);
        }

        [HttpPost]
        public ActionResult Edit(WaterShedEditViewModel Model)
        {
            if (_waterShedRepo.IsWaterShedDescriptionDuplicate(Model.WaterShedDescription))
            {
                Model.ShowMessageDescription = true;
                Model.MessageDescription = "The Water Shed Description already exists. Please enter a different one.";

                return View(Model);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    int id = 0;
                    if (Model.WaterShedID == 0) //new
                    {
                        int waterShedID = _waterShedRepo.GetNextWaterShedID();
                        REF_LOCATION_TYPE_TB waterShed = new REF_LOCATION_TYPE_TB()
                        {
                            B_INACTIVE = false,
                            DT_ENTERED = DateTime.UtcNow,
                            DT_MODIFIED = DateTime.UtcNow,
                            SZ_DESCRIPTION = Model.WaterShedDescription,
                            SZ_ENTERED_BY = _modifiedBy,
                            SZ_MODIFIED_BY = _modifiedBy
                        };
                        _uow.Repository<REF_LOCATION_TYPE_TB>().Add(waterShed);
                        _uow.SaveChanges();
                        REF_LOCATION_TYPE_TB waterShedFound = _uow.Repository<REF_LOCATION_TYPE_TB>().Find(u => u.SZ_ENTERED_BY == _modifiedBy
                            && u.SZ_MODIFIED_BY == _modifiedBy && u.SZ_DESCRIPTION == Model.WaterShedDescription
                            ).FirstOrDefault();
                        id = waterShedFound.N_LOCATION_TYPE_SYSID;
                    }
                    else //edit
                    {
                        REF_LOCATION_TYPE_TB waterShed = _uow.Repository<REF_LOCATION_TYPE_TB>().GetById(Model.WaterShedID);
                        waterShed.SZ_MODIFIED_BY = _modifiedBy;
                        waterShed.DT_MODIFIED = DateTime.UtcNow;
                        waterShed.SZ_DESCRIPTION = Model.WaterShedDescription;

                        _uow.Repository<REF_LOCATION_TYPE_TB>().Update(waterShed);
                        _uow.SaveChanges();
                        id = Model.WaterShedID;
                    }

                    return RedirectToAction("Index", new { ID = id });
                }
            }

            return View(Model);
        }

        [HttpGet]
        public ActionResult Delete(string ID)
        {
            try
            {
                REF_LOCATION_TYPE_TB waterShed = _uow.Repository<REF_LOCATION_TYPE_TB>().GetById(Convert.ToInt32(ID));
                WaterShedDeleteViewModel waterShedDeleteViewModel = new WaterShedDeleteViewModel()
                {
                    WaterShedID = waterShed.N_LOCATION_TYPE_SYSID,
                    WaterShedDescription = waterShed.SZ_DESCRIPTION,
                    MessageDescription = "",
                    ShowMessageDescription = false
                };

                return View(waterShedDeleteViewModel);
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewBag.Message = "Function: WaterShedController.Delete_GET\n\nError: " + ex.Message;
                }
                else
                {
                    ViewBag.Message = "Function: WaterShedController.Delete_GET\n\nError: " + (ex.Message + "\n\nInnerException: " + ex.InnerException.Message);
                };
                Session["ErrorMessage"] = ViewBag.Message;
                return RedirectToAction("InternalServerError", "Error");
            };
        }

        [HttpPost]
        public ActionResult Delete(WaterShedDeleteViewModel model)
        {
            try
            {
                int id = Convert.ToInt32(model.WaterShedID);
                if (_uow.Repository<REF_LOCATION_TB>().Find(u => u.N_LOCATION_TYPE_SYSID == id).Count() > 0)
                {
                    model.ShowMessageDescription = true;
                    model.MessageDescription = "Location records exist for this water shed. Sorry, the water shed can not be deleted.";

                    return View(model);
                }
                else
                {
                    _uow.Repository<REF_LOCATION_TYPE_TB>().Delete(id);
                    _uow.SaveChanges();

                    return RedirectToAction("Index", new { ID = id });
                }
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewBag.Message = "Function: WaterShedController.Delete_POST\n\nError: " + ex.Message;
                }
                else
                {
                    ViewBag.Message = "Function: WaterShedController.Delete_POST\n\nError: " + (ex.Message + "\n\nInnerException: " + ex.InnerException.Message);
                };
                Session["ErrorMessage"] = ViewBag.Message;
                return RedirectToAction("InternalServerError", "Error");
            };    
        }
    }
}

WaterQuality/Views/WaterShed/Delete.cshtml
@using EHWaterQuality.ViewModels
@model WaterShedDeleteViewModel
@{
    ViewBag.Title = "Delete Water Shed";
}

<!-- BEGIN PAGE CONTENT -->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="row">
        @using (Html.BeginForm("Delete", "WaterShed", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
        {
            <div class="row">
                <label class="control-label col-md-2">Water Shed Description</label>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.WaterShedDescription)
                    @Html.HiddenFor(model => model.WaterShedDescription)
                    @Html.HiddenFor(model => model.WaterShedID)
                    @if (Model.ShowMessageDescription == true)
                    {
                        <span style="color:red">@Html.DisplayFor(m => m.MessageDescription)</span>
                    }
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <button type="submit" class="btn blue">Delete</button>
                    <button type="button" class="btn blue" id="back">Back</button>
                </div>
            </div>
        }
    </div>
    @section PageLevelScripts {
        <script>
            $(document).ready(function () {
                $("#back").on('click', function () {
                    var model = @Html.Raw(Json.Encode(Model));
                    var id = model.WaterShedID;
                    var url = '@Url.Action("Index", "WaterShed", new { ID = "_id_" })'.replace('_id_', id);
                    window.location.href = url;
                })
            })
        </script>
    }
</body>
</html>
<!-- END PAGE CONTENT -->

WaterQuality/Views/WaterShed/Edit.cshtml
@using EHWaterQuality.ViewModels
@model WaterShedEditViewModel
@{
    ViewBag.Title = "Edit / New Water Shed";
}

<!-- BEGIN PAGE CONTENT -->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="row">
        @using (Html.BeginForm("Edit", "WaterShed", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
        {
            <div class="row">
                <label class="control-label col-md-2"><span class="required">* </span>Water Shed Description</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.WaterShedDescription, new { style = "width:750px;" })
                    <span style="color:red">@Html.ValidationMessageFor(model => model.WaterShedDescription)</span>
                    @Html.HiddenFor(model => model.WaterShedID)
                    @if (Model.ShowMessageDescription == true)
                    {
                        <span style="color:red">@Html.DisplayFor(m => m.MessageDescription)</span>
                    }
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <button type="submit" class="btn blue">Save</button>
                    <button type="button" class="btn blue" id="back">Back</button>
                </div>
            </div>
        }
    </div>
    @section PageLevelScripts {
        <script>
            $(document).ready(function () {
                $("#back").on('click', function () {
                    var model = @Html.Raw(Json.Encode(Model));
                    var id = model.WaterShedID;
                    var url = '@Url.Action("Index", "WaterShed", new { ID = "_id_" })'.replace('_id_', id);
                    window.location.href = url;
                })
            })
        </script>
    }
</body>
</html>
<!-- END PAGE CONTENT -->

WaterQuality/Views/WaterShed/Index.cshtml
@using EHWaterQuality.ViewModels
@model WaterShedIndexViewModel
@{
    ViewBag.Title = "Maintain Water Sheds";
}

<!-- BEGIN PAGE CONTENT -->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-edit"></i>Water Sheds
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                    Select Water Shed and <button type="button" class="btn blue" id="edit">Edit</button>
                    <button type="button" class="btn blue" id="delete">Delete</button> |
                    <button type="button" id="new" class="btn blue">
                        New Water Shed <i class="fa fa-plus"></i>
                    </button>
                    <br />
                    <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                        <thead>
                            <tr>
                                <th>
                                    Select
                                </th>
                                <th>
                                    Water Shed Description
                                </th>
                            </tr>
                        </thead>
                        <tbody id="waterSheds"></tbody>
                        <tfoot>
                            <tr>
                                <th>
                                    Select
                                </th>
                                <th>
                                    Water Shed Description
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                    Select Water Shed and <button type="button" class="btn blue" id="edit2">Edit</button>
                    <button type="button" class="btn blue" id="delete2">Delete</button> |
                    <button type="button" id="new2" class="btn blue">
                        New Water Shed <i class="fa fa-plus"></i>
                    </button>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    @section PageLevelScripts {
        <script>
    $(document).ready(function () {
        GetWaterSheds();
    })

    $('#edit').click(function () {
        EditWaterShed();
    })

    $('#edit2').click(function () {
        EditWaterShed();
    })

    $('#delete').click(function () {
        DeleteWaterShed();
    })

    $('#delete2').click(function () {
        DeleteWaterShed();
    })

    $('#new').click(function () {
        NewWaterShed();
    })

    $('#new2').click(function () {
        NewWaterShed();
    })

    function GetWaterSheds() {
        $.ajaxSetup({ cache: false });
        var url = '@Url.Action("GetWaterSheds", "WaterShed")';
        $.getJSON(url, function (response) {
            if (response.length) {
                var row = "";
                $.each(response, function (index, item) {
                    row += "<tr><td><input type='checkbox' id='waterShedCheckbox' name='" + item.WaterShedID + "'" +
                        " class='my_chkBox' /></td><td>" + item.WaterShedDescription +
                        "</td></tr>";
                })
                $("#waterSheds").html(row);
                $("#waterSheds").find(":checkbox").click(function () {
                    $("#waterSheds").find(":checkbox").removeAttr("checked");
                    $(this).prop("checked", true);
                })
                SelectedWaterShed();
            }
            else {
                $("#waterSheds").html("<div class='col-md-12'><h2 style='color:red'>No records found.</h2></div>");
            }
        });
    }

    function SelectedWaterShed() {
        var model = @Html.Raw(Json.Encode(Model));
        var id = model.ID;
        if (id != "0") {
            $('#waterSheds').find(':checkbox').each(function () {
                if ($(this).prop("name").toString() == id) {
                    $(this).prop('checked', true);
                }
            })
        }
    }

    function EditWaterShed() {
        var id = 0;
        $('#waterSheds').find(':checkbox').each(function () {
            if ($(this).prop("checked") == true) {
                id = $(this).prop("name").toString();
                return false;
            }
        })
        if (id == 0) {
            alert("Please select a Water Shed for edit");
        }
        else {
            var url = '@Url.Action("Edit", "WaterShed", new { ID = "_id_" })'.replace('_id_', id);
            window.location.href = url;
        }
    }

    function DeleteWaterShed() {
        var id = 0;
        $('#waterSheds').find(':checkbox').each(function () {
            if ($(this).prop("checked") == true) {
                id = $(this).prop("name").toString();
                return false;
            }
        })
        if (id == 0) {
            alert("Please select a Water Shed for delete");
        }
        else {
            var url = '@Url.Action("Delete", "WaterShed", new { ID = "_id_" })'.replace('_id_', id);
            window.location.href = url;
        }
    }

    function NewWaterShed() {
        var id = 0;
        var url = '@Url.Action("Edit", "WaterShed", new { ID = "_id_" })'.replace('_id_', id);
        window.location.href = url;
    }
        </script>
    }
</body>
</html>
<!-- END PAGE CONTENT -->